// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
	"time"
)

type Asset struct {
	ID     int64   `json:"id"`
	UserID int64   `json:"user_id"`
	Name   string  `json:"name"`
	Amount float64 `json:"amount"`
}

type Budget struct {
	ID         int64     `json:"id"`
	CategoryID int64     `json:"category_id"`
	Amount     float64   `json:"amount"`
	StartDate  time.Time `json:"start_date"`
	EndDate    time.Time `json:"end_date"`
}

type Category struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

type Goal struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Type      string    `json:"type"`
	Amount    float64   `json:"amount"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	Status    string    `json:"status"`
}

type Liability struct {
	ID     int64   `json:"id"`
	UserID int64   `json:"user_id"`
	Name   string  `json:"name"`
	Amount float64 `json:"amount"`
}

type Transaction struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	CategoryID  int64          `json:"category_id"`
	Name        string         `json:"name"`
	Amount      float64        `json:"amount"`
	Description sql.NullString `json:"description"`
	Type        string         `json:"type"`
	Date        time.Time      `json:"date"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type User struct {
	ID        int64     `json:"id"`
	ClerkID   string    `json:"clerk_id"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
